name: .NET Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check .NET
        run: dotnet --info

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Publish Executable
        run: dotnet publish --configuration Release --output publish -r linux-x64 --self-contained true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-demo
          path: publish/
